variables:
  VERSION: "1.0"
  BUILD_NUMBER: ${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA:0:8}-${CI_PIPELINE_ID}
  FULL_VERSION: ${VERSION}-${BUILD_NUMBER}
  LC_ALL: 'en_US.UTF-8'
  FASTLANE_EXPLICIT_OPEN_SIMULATOR: "true"

cache:
  paths:
    - vendor/

stages:
  - build-framework

before_script:
  - rbenv install --skip-existing
  - gem install bundler --force
  - ruby -v
  - which ruby
  - bundle install --path vendor/bundle

build-salesforce-wrapper-framework:
  tags:
    - xcode9
  stage: build-framework
  artifacts:
    paths:
      - Output
    expire_in: 1 week
  script:
    - bundle exec fastlane framework
